version: "SecDev"
requirements:
  python: "3.6"
  go: "1.12"
  pylint: "1.9"
  golangci-lint: "1.1"
  git: "2.2"
  dep: "0.5"
  docker: "18.0"
  docker-compose: "1.2"
  docker-machine: "0.16"
  micros: "6.8"
packages:
  default:
    installer: brew
  python:
    display: Python
    command: python3
    version_extraction: "--version | cut -d ' ' -f2 2>&1"
  go:
    display: Golang
    command: go
    version_extraction: "version | cut -d ' ' -f3 | tr -d 'go'"
  pylint:
    display: Pylint
    installer: pip3
    command: pylint
    version_extraction: "--version 2>&1 | sed -n 2p | cut -d ' ' -f2 | sed -n 1p | tr -d ','"
  golangci-lint:
    display: Golangci-lint
    command: golangci-lint
    version_extraction: "--version | cut -d ' ' -f4"
  git:
    display: Git
    command: git
    version_extraction: "--version | cut -d ' ' -f3"
  dep:
    display: Dep
    command: dep
    version_extraction: "version | cut -d ':' -f2 | sed -n 2p | tr -d ' v'"
  docker:
    display: Docker
    command: docker
    version_extraction:  "--version | cut -d ' ' -f3 | tr -d ','"
  docker-compose:
    display: Docker-compose
    command: docker-compose
    version_extraction: "--version | cut -d ' ' -f3 | tr -d ','"
  docker-machine:
    display: Docker-machine
    command: docker-machine
    version_extraction: "--version | cut -d ' ' -f3 | tr -d ','"
  micros:
    display: Micros
    command: micros
    install_command: micros-cli # substitutes for command, in the case the package is installed with a different name
    version_extraction: 'version'
installers:
  brew:
    command: brew install
    configurations:
      - "brew tap atlassian/micros ssh://git@stash.atlassian.com:7997/micros/micros-cli-homebrew-tap.git"
      - "brew tap golangci/tap"
  pip3:
    command: pip3 install